### PR TITLE
fix: type aliases

### LINKED ISSUE #46: regression with go1.23 and v1.0.0
The following elements are not reported when using go1.23 and v1.0.0

```go
package sandbox

import (
	"io"
)

type User struct{}

type mapAlias = map[int]*User

type closerAlias = io.Closer

type Checker interface{ Check() }

type checkerAlias = Checker

func anyType() (any, error) {
	return nil, nil // want "return both a `nil` error and an invalid value: use a sentinel error instead"
}

func m3() (mapAlias, error) {
	return nil, nil // want "return both a `nil` error and an invalid value: use a sentinel error instead"
}

func ifaceTypeAliasedExtPkg() (closerAlias, error) {
	return nil, nil // want "return both a `nil` error and an invalid value: use a sentinel error instead"
}

func ifaceTypeAliased() (checkerAlias, error) {
	return nil, nil // want "return both a `nil` error and an invalid value: use a sentinel error instead"
}
```

### PR DESCRIPTION
**Pull request by ldez**
Fixes #46

### CODE REVIEW

**Review by Antonboom — CHANGES_REQUESTED** [review]
Thank you, @ldez 

Can I ask you to copy-paste your example from issue in new testcase (`pkg/analyzer/testdata/src`)? And check change through TDD

Thanks 🙏

**Comment by ldez** [comment]
The examples come from the test cases of golangci-lint, I thought they were here too.

**Comment by ldez** [comment]
They are already inside your repo.

**Comment by ldez** [comment]
To reproduce:
- modify the min Go version inside the `go.mod` to `go1.23.0`
- run the tests

```console
$ go test ./...
?       github.com/Antonboom/nilnil     [no test files]
--- FAIL: TestNilNil (0.93s)
    analysistest.go:614: examples/positive.go:68: no diagnostic was reported matching "return both a `nil` error and an invalid value: use a sentinel error instead"
    analysistest.go:614: examples/positive.go:82: no diagnostic was reported matching "return both a `nil` error and an invalid value: use a sentinel error instead"
    analysistest.go:614: examples/positive_external_types.go:35: no diagnostic was reported matching "return both a `nil` error and an invalid value: use a sentinel error instead"
    analysistest.go:614: examples/positive_own_types.go:34: no diagnostic was reported matching "return both a `nil` error and an invalid value: use a sentinel error instead"
FAIL
FAIL    github.com/Antonboom/nilnil/pkg/analyzer        0.947s
FAIL
```

**Comment by Antonboom** [comment]
> They are already inside your repo.

Oh, thanks, I completely forgot about it 🤦 
Thanks for MR and digging

**Pull request merged**
